### PR TITLE
392_Is Subsequence.cpp

### PR DESCRIPTION
**Pull request by deepakmaur**
This is the solution of the given problem

In this solution   If Second string is Subsequence of First string it will return true

### CODE REVIEW

**Review by iVaR-eDoCeD — COMMENTED** [review]
Please dont make changes to others files !! or else i will have to cancel your PR's

**Review by iVaR-eDoCeD — APPROVED** [review]
This one is okayy !! But please abstain from changing other peoples solutions

**Comment by deepakmaur** [comment]
Thankyou for the guidence And sorry for my error sir

**Comment by deepakmaur** [comment]
I am actually Newbie in Open Source so please don't cancel my PR

**Comment by deepakmaur** [comment]
Sorry I have  requested for Review

**Review by iVaR-eDoCeD — APPROVED** [review]
Done !!

**Comment by iVaR-eDoCeD** [comment]
Im not sir its okkie, i just wanted to make sure the repository is good so !!

**Pull request merged**
